### ISSUE TITLE
[Plume-admin] Double install de GuiceServicesModule ?

### ISSUE THREAD

**Issue by dokor** [Coreoz/Plume-admin#20]
Dans GuiceAdminWsModule

Il y a : 
```		
                install(new GuiceServicesModule());           
		install(new GuiceAdminSecurityModule());
```

Cependant, GuiceAdminSecurityModule fait également l'install de GuiceServicesModule

```
public class GuiceAdminSecurityModule extends AbstractModule {

	@Override
	protected void configure() {
		install(new GuiceServicesModule());
	}

}
```

Est ce normal et volontaire d'avoir deux fois l'install ? 

(Antoine Le Louët)

**Comment by amanteaux** [comment]
Hello Antoine !

Sans que ce soit forcément volontaire, cela est normalement acceptable dans l'utilisation de Guice (plusieurs modules différents peuvent avoir la même dépendance) et ne pose de pas de problème.

Tu as rencontré un problème avec ça ?

**Comment by dokor** [comment]
Hello Aurélien, 

Ca marche, merci de ta réponse :)
Non pas de souci particulier avec cela, ca m'a juste étonné haha.

**Comment by amanteaux** [comment]
Je ferme, je reste dispo si besoin
